# Generated by Django 3.1.6 on 2021-04-04 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('experience', models.PositiveBigIntegerField(default=0)),
                ('hit_points', models.PositiveBigIntegerField(default=1)),
                ('damage', models.PositiveBigIntegerField(default=0)),
                ('image', models.ImageField(upload_to='enemies')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('experience', models.PositiveBigIntegerField(default=0)),
                ('x', models.PositiveSmallIntegerField(default=1)),
                ('y', models.PositiveSmallIntegerField(default=1)),
                ('active', models.CharField(default='0', max_length=31)),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='engine.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField(default=1)),
                ('y', models.PositiveSmallIntegerField(default=1)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.enemy')),
                ('location_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engine.location')),
            ],
        ),
    ]
