# Generated by Django 3.1.6 on 2021-04-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20210406_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationspot',
            name='door_direction',
            field=models.PositiveSmallIntegerField(choices=[(1, 'up'), (2, 'left'), (3, 'down'), (4, 'right')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='gold',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='premium_gold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
