# Generated by Django 3.1.6 on 2021-04-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_locationspot_collision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationspot',
            name='door_direction',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'up'), (2, 'left'), (3, 'down'), (4, 'right')], null=True),
        ),
    ]
