# Generated by Django 3.1.6 on 2021-04-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20210426_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='armor',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemy',
            name='attack_speed',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='player',
            name='armor',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='attack_speed',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='player',
            name='current_hit_points',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='damage',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='hit_points',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
